import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import ReduxWrapper from "./components/ReduxWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Wave Synth",
  description: "Generated by create next app",
  icons: {
    icon: "/next.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxWrapper>
          <div className="flex flex-col min-h-screen bg-gray-900">
            <NavBar />
            <main className="flex-grow grid gap-1 m-10">{children}</main>
            <Footer />
          </div>
        </ReduxWrapper>
      </body>
    </html>
  );
}
